services:
  web:
    build: ./warmify
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./warmify/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=warmify
      - POSTGRES_PASSWORD=warmify
      - POSTGRES_DB=warmify_db

  redis:
    image: redis
  
  celery:
    build: ./warmify
    command: celery --app=warmify worker --loglevel=info
    volumes:
      - ./warmify:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

volumes:
  postgres_data: