# Generated by Django 5.0.2 on 2024-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmify_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='name',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='metadata',
            field=models.JSONField(default={}),
        ),
    ]
