# Generated by Django 5.0.2 on 2024-04-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0005_schedule_temperature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("recorded_device_temperature", models.IntegerField()),
                ("recorded_controller_temperature", models.IntegerField()),
                ("recorded_waterlevel", models.IntegerField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warmify_core.iotdevice",
                    ),
                ),
            ],
        ),
    ]
