# Generated by Django 5.0.2 on 2024-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0006_ping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="recorded_controller_temperature",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ping",
            name="recorded_device_temperature",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ping",
            name="recorded_waterlevel",
            field=models.IntegerField(null=True),
        ),
    ]
