# Generated by Django 5.0.2 on 2024-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "SUCCESS"),
                    ("info", "INFO"),
                    ("warning", "WARNING"),
                    ("danger", "DANGER"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
