# Generated by Django 5.0.2 on 2024-05-03 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0009_notification_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleinterval",
            name="device",
        ),
        migrations.RemoveField(
            model_name="temperature",
            name="device",
        ),
        migrations.AddField(
            model_name="ping",
            name="is_on_heater",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="ping",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="ScheduleInterval",
        ),
        migrations.DeleteModel(
            name="Temperature",
        ),
    ]
