# Generated by Django 5.0.2 on 2024-05-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0010_remove_scheduleinterval_device_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ping",
            old_name="recorded_device_temperature",
            new_name="recorded_heater_temperature",
        ),
    ]
