# Generated by Django 5.0.2 on 2024-05-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warmify_core",
            "0011_rename_recorded_device_temperature_ping_recorded_heater_temperature",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("heater_not_working", "Heater is not working"),
                    ("empty_tank", "water tank is empty"),
                    ("custom", "Custom notification"),
                ],
                default="custom",
                max_length=40,
            ),
        ),
    ]
