# Generated by Django 4.2.11 on 2024-05-12 08:45

from django.db import migrations, models
import warmify_core.models.event
import warmify_core.models.ping
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("warmify_core", "0012_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.now,
                verbose_name="event timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="ping",
            name="timestamp",
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
